version: "3"
services:
  darts-matcher-legacy-api:
    restart: always
    image: darts-matcher-legacy-api
    container_name: darts-matcher-legacy-api
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URI=mongodb://localhost:27017/darts-matcher-legacy
      - JWK_KEYSTORE_ALIAS=darts-matcher-alias
      - JWK_KEYSTORE_PASS=secret
      - JWK_KEYSTORE_PATH=classpath:keystore/darts-matcher-dev-jwk.jks
      - JWK_SET_URI=http://localhost:8080/.well-known/jwks.json
      - EMAIL_USERNAME=DUMMY_EMAIL@EMAIL.COM
      - EMAIL_PASSWORD=DUMMY_EMAIL_PASSWORD
    ports:
      - "8080:8080"
